### ISSUE TITLE
Randomly will not resume from stop cleanly

### ISSUE THREAD

**Issue by Avi0n** [MoreTore/openpilot#18]
### Describe the bug

There are two issues I've experienced. Both while OP is engaged.

Issue 1 (more severe one, but no logs yet. Will provide logs when issue happens again.):
- Come to a complete stop with lead vehicle
- Lead vehicle departs
- Observe FrogPilot press gas slightly, then slam on brakes
- From this point, FrogPilot will not resume and you must completely disengage FrogPilot by pressing the brake. At this point the car will move again. If you press the accelerator without pressing the brake first, the car will stay still but the engine will rev.

Issue 2 (logs provided):
- Come to a complete stop with lead vehicle
- Lead vehicle departs
- Observe FrogPilot press gas slightly, then brake to a stop (didn't feel like a slam)
- From this point, FrogPilot will not resume and you must press the accelerator to resume movement

### Provide a route where the issue occurs

20e394a46517a2ad/2024-03-20--09-38-45/12

### openpilot version

f1b6bf66bae8ba8a4bbb3114b6b679f0b14aa091

### Additional info

Branch: mazda-frogpilot-dev
Device: Comma 3

**Comment by MoreTore** [comment]
I'll try to look at this on the weekend. I have had something this happen to me but it didn't slam on the brakes and I just override the gas because I thought it was just the model being dumb.

**Comment by Avi0n** [comment]
These issues have been happening to me over the past few months, and on the non-FrogPilot branches too, IIRC. Unfortunately I haven't had the time to report until now.

I also mistyped on the descriptions of the issues (now corrected), only Issue 1 causes brake slamming. I will try to get logs soonish, assuming it happens again.

**Comment by MoreTore** [comment]
Hey I have pushed a potential fix for this https://github.com/MoreTore/openpilot/commit/44c62add4aa768b7808c44d01b20fb00a1eea1c7

Let me know if the issue persists or if there are any new issues resulting from this fix.
