### ISSUE TITLE
Control mismatch when "disengage on accelerator press" is disabled

### ISSUE THREAD

**Issue by phealy** [MoreTore/openpilot#3]
### Describe the bug

When I try to start driving with "disengage on accelerator press" disabled, I receive a control mismatch error. Enabling the feature, powering the car off and on, and then starting a drive again will work.

### Which car does this affect?

2019 Mazda CX-5 Signature with TI

### Provide a route where the issue occurs

cb8769500d8906ce|2023-05-09--18-49-01--0

### openpilot version

43290dd01e28062e9c692af2b9739b960a324443

**Comment by MoreTore** [comment]
I wonder if this is a bug with stock Openpilot https://github.com/MoreTore/openpilot/blob/b78a6671f8ac5ed5c75f687e0b626135a076a64f/panda/board/main_comms.h#L403

**Comment by phealy** [comment]
I don't think so - the way I read it you have to set the alternative experience before you set the car safety mode - [which is what the code does](https://github.com/MoreTore/openpilot/blob/bda33a942f176f329c9a86e405b28593dfde05d6/selfdrive/boardd/boardd.cc#L182)

**Comment by AndrewEAUS** [comment]
I ran stock for a little bit and the disengage on accelerator press worked correctly with no error (and was great). Definitely not a stock bug.

**Comment by MoreTore** [comment]
> I ran stock for a little bit and the disengage on accelerator press worked correctly with no error (and was great). Definitely not a stock bug.

Oh wait I read the issue wrong. I thought it would work after you restart the ignition with it disabled. I might have an idea of what is wrong.

**Comment by phealy** [comment]
Yeah, to be clear: when the system is set to stay running on accelerator press, I only get an LKAS error, even after rebooting.

**Comment by MoreTore** [comment]
Ok i figured out the issue. I will push an update to newcan-9.2-master

**Comment by MoreTore** [comment]
https://github.com/MoreTore/openpilot/commit/cf7caa42b0a9d1dd76483eeb939c791239727498
