### ISSUE TITLE
Lateral control not possible with ti

### ISSUE THREAD

**Issue by AXLETX** [MoreTore/openpilot#4]
### Describe the bug

After adding TI to the original LKAS, there is no way to control the lateral direction. The original LKAS also fails

### Provide a route where the issue occurs

ea4f9db551dbe523|2023-05-28--06-30-50

### openpilot version

newcan-9.0-nomrcc

### Additional info

2017 MAZDA3

I used the OP again today, using the 9.0 branch
1. Install ti without installing op, the original lkas can work normally
2. Install ti and op, the original lkas cannot be used
Driver monitoring on op does not work

**Comment by MoreTore** [comment]
Can you try the latest update?
https://github.com/MoreTore/openpilot/tree/newcan-9.0-nomrcc
you can check for update from the comma 3 user interface

**Comment by AXLETX** [comment]
Thank you for your help, there are still some small problems after the update
Cruise control won't start
There may be a bug in the setting of disengage on accelerator pedal
ea4f9db551dbe523|2023-06-04--19-27-53
ea4f9db551dbe523|2023-06-05--19-38-16
![S__7610373](https://github.com/MoreTore/openpilot/assets/129540807/89bd0f87-04ff-47c1-8f5e-33125aa0f56e)

**Comment by MoreTore** [comment]
Resolved. https://github.com/MoreTore/openpilot/commit/2574cd90ff45ea434e812854e48663c7f2b52eb3
