### ISSUE TITLE
Mazd master not working 

### ISSUE THREAD

**Issue by kaledz** [MoreTore/openpilot#7]
### Describe the bug

Every time I install the Mazda master fork it give me the error on start that this car is not supported and will only function in dash am mode. I did the system reset and install as instructed with the YouTube video but no luck on detecting the vechicle. Does anybody have any recommendations or do I need to fingerprint for each new fork?

### Provide a route where the issue occurs

?

### openpilot version

Mazda-Master

**Comment by MoreTore** [comment]
I have modified the fingerprinting. Can you please try updating mazda-master and let me know if it works this time? I assume you are not using comma power and this may be the issue.

**Comment by kaledz** [comment]
> I have modified the fingerprinting. Can you please try updating mazda-master and let me know if it works this time? I assume you are not using comma power and this may be the issue.

I am not using comma power. I take it out of the car to do the updates. I just updated to Mazda - Master but it still says unsupported.

**Comment by kaledz** [comment]
> I have modified the fingerprinting. Can you please try updating mazda-master and let me know if it works this time? I assume you are not using comma power and this may be the issue.

Updated log from recently reimstalled Mazda master fork. Still not recognized by the car.

log: accelerometercameraOdometrycancarControlcarEventscarParamscarStateclockscontrolsStatedeviceStatedriverCameraStatedriverEncodeIdxdriverMonitoringStatedriverStateV2errorLogMessagegnssMeasurementsgpsLocationExternalgyroscopeinitDatalateralPlanlightSensorliveCalibrationliveLocationKalmanliveParametersliveTorqueParameterslongitudinalPlanmagnetometermanagerStatemicrophonemodelV2navInstructionpandaStatesperipheralStateqRoadEncodeIdxradarStateroadCameraStateroadEncodeIdxsendcansentineltemperatureSensorthumbnailuiDebuguiPlanwideRoadCameraStatewideRoadEncodeIdx{'carParams': {'alternativeExperience': 1, 'autoResumeSng': True, 'carFingerprint': 'mock', 'carFw': [{'address': 1840, 'brand': 'mazda', 'bus': 0, 'ecu': 'eps', 'fwVersion': b'BCKA-3216X-E\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'logging': False, 'obdMultiplexing': True, 'request': [b'>\x00', b'"\xf1\x88'], 'responseAddress': 1848, 'subAddress': 0}, {'address': 1888, 'brand': 'mazda', 'bus': 0, 'ecu': 'abs', 'fwVersion': b'BHCB-4300F-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'logging': False, 'obdMultiplexing': True, 'request': [b'>\x00', b'"\xf1\x88'], 'responseAddress': 1896, 'subAddress': 0}, {'address': 1798, 'brand': 'mazda', 'bus': 0, 'ecu': 'fwdCamera', 'fwVersion': b'BDGF-67WK2-K\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'logging': False, 'obdMultiplexing': True, 'request': [b'>\x00', b'"\xf1\x88'], 'responseAddress': 1806, 'subAddress': 0}, {'address': 1892, 'brand': 'mazda', 'bus': 0, 'ecu': 'fwdRadar', 'fwVersion': b'BDTS-67XK2-E\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'logging': False, 'obdMultiplexing': True, 'request': [b'>\x00', b'"\xf1\x88'], 'responseAddress': 1900, 'subAddress': 0}, {'address': 1840, 'brand': 'ford', 'bus': 0, 'ecu': 'eps', 'fwVersion': b'BCKA-3216X-E\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'logging': False, 'obdMultiplexing': True, 'request': [b'>\x00', b'"\xf1\x88'], 'responseAddress': 1848, 'subAddress': 0}, {'address': 1888, 'brand': 'ford', 'bus': 0, 'ecu': 'abs', 'fwVersion': b'BHCB-4300F-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'logging': False, 'obdMultiplexing': True, 'request': [b'>\x00', b'"\xf1\x88'], 'responseAddress': 1896, 'subAddress': 0}, {'address': 1798, 'brand': 'ford', 'bus': 0, 'ecu': 'fwdCamera', 'fwVersion': b'BDGF-67WK2-K\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'logging': False, 'obdMultiplexing': True, 'request': [b'>\x00', b'"\xf1\x88'], 'responseAddress': 1806, 'subAddress': 0}, {'address': 1892, 'brand': 'ford', 'bus': 0, 'ecu': 'fwdRadar', 'fwVersion': b'BDTS-67XK2-E\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'logging': False, 'obdMultiplexing': True, 'request': [b'>\x00', b'"\xf1\x88'], 'responseAddress': 1900, 'subAddress': 0}], 'carName': 'mock', 'carVin': '00000000000000000', 'centerToFront': 1.350000023841858, 'communityFeatureDEPRECATED': False, 'dashcamOnly': False, 'directAccelControlDEPRECATED': False, 'enableApgsDEPRECATED': False, 'enableBsm': False, 'enableCameraDEPRECATED': False, 'enableDsu': False, 'enableGasInterceptor': False, 'experimentalLongitudinalAvailable': False, 'fingerprintSource': 'can', 'flags': 0, 'fuzzyFingerprint': False, 'hasStockCameraDEPRECATED': False, 'isPandaBlackDEPRECATED': False, 'lateralTuning': {'pid': {'kf': 0.0}}, 'longitudinalActuatorDelayLowerBound': 0.15000000596046448, 'longitudinalActuatorDelayUpperBound': 0.15000000596046448, 'longitudinalTuning': {'deadzoneBP': [0.0], 'deadzoneV': [0.0], 'kf': 1.0, 'kiBP': [0.0], 'kiV': [1.0], 'kpBP': [0.0], 'kpV': [1.0]}, 'mass': 1700.0, 'maxLateralAccel': 10.0, 'maxSteeringAngleDegDEPRECATED': 0.0, 'minEnableSpeed': -1.0, 'minSpeedCanDEPRECATED': 0.0, 'minSteerSpeed': 0.0, 'networkLocation': 'fwdCamera', 'notCar': False, 'openpilotLongitudinalControl': False, 'pcmCruise': True, 'radarTimeStep': 0.05000000074505806, 'radarUnavailable': False, 'rotationalInertia': 2906.976806640625, 'safetyConfigs': [{'safetyModel': 'noOutput', 'safetyParam': 0, 'safetyParam2DEPRECATED': 0, 'safetyParamDEPRECATED': 0}], 'safetyModelDEPRECATED': 'silent', 'safetyModelPassiveDEPRECATED': 'silent', 'safetyParamDEPRECATED': 0, 'startAccel': 0.0, 'startingAccelRateDEPRECATED': 0.0, 'startingState': False, 'steerActuatorDelay': 0.0, 'steerControlType': 'torque', 'steerLimitAlert': False, 'steerLimitTimer': 1.0, 'steerRateCostDEPRECATED': 0.0, 'steerRatio': 13.0, 'steerRatioRear': 0.0, 'stopAccel': -2.0, 'stoppingControl': True, 'stoppingDecelRate': 0.800000011920929, 'tireStiffnessFront': 1000000.0, 'tireStiffnessRear': 1000000.0, 'transmissionType': 'unknown', 'vEgoStarting': 0.5, 'vEgoStopping': 0.5, 'wheelSpeedFactor': 1.0, 'wheelbase': 2.700000047683716}, 'logMonoTime': 60582340178, 'valid': True} {'carParams': {'alternativeExperience': 1, 'autoResumeSng': True, 'carFingerprint': 'mock', 'carFw': [{'address': 1840, 'brand': 'mazda', 'bus': 0, 'ecu': 'eps', 'fwVersion': b'BCKA-3216X-E\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'logging': False, 'obdMultiplexing': True, 'request': [b'>\x00', b'"\xf1\x88'], 'responseAddress': 1848, 'subAddress': 0}, {'address': 1888, 'brand': 'mazda', 'bus': 0, 'ecu': 'abs', 'fwVersion': b'BHCB-4300F-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'logging': False, 'obdMultiplexing': True, 'request': [b'>\x00', b'"\xf1\x88'], 'responseAddress': 1896, 'subAddress': 0}, {'address': 1798, 'brand': 'mazda', 'bus': 0, 'ecu': 'fwdCamera', 'fwVersion': b'BDGF-67WK2-K\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'logging': False, 'obdMultiplexing': True, 'request': [b'>\x00', b'"\xf1\x88'], 'responseAddress': 1806, 'subAddress': 0}, {'address': 1892, 'brand': 'mazda', 'bus': 0, 'ecu': 'fwdRadar', 'fwVersion': b'BDTS-67XK2-E\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'logging': False, 'obdMultiplexing': True, 'request': [b'>\x00', b'"\xf1\x88'], 'responseAddress': 1900, 'subAddress': 0}, {'address': 1840, 'brand': 'ford', 'bus': 0, 'ecu': 'eps', 'fwVersion': b'BCKA-3216X-E\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'logging': False, 'obdMultiplexing': True, 'request': [b'>\x00', b'"\xf1\x88'], 'responseAddress': 1848, 'subAddress': 0}, {'address': 1888, 'brand': 'ford', 'bus': 0, 'ecu': 'abs', 'fwVersion': b'BHCB-4300F-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'logging': False, 'obdMultiplexing': True, 'request': [b'>\x00', b'"\xf1\x88'], 'responseAddress': 1896, 'subAddress': 0}, {'address': 1798, 'brand': 'ford', 'bus': 0, 'ecu': 'fwdCamera', 'fwVersion': b'BDGF-67WK2-K\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'logging': False, 'obdMultiplexing': True, 'request': [b'>\x00', b'"\xf1\x88'], 'responseAddress': 1806, 'subAddress': 0}, {'address': 1892, 'brand': 'ford', 'bus': 0, 'ecu': 'fwdRadar', 'fwVersion': b'BDTS-67XK2-E\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'logging': False, 'obdMultiplexing': True, 'request': [b'>\x00', b'"\xf1\x88'], 'responseAddress': 1900, 'subAddress': 0}], 'carName': 'mock', 'carVin': '00000000000000000', 'centerToFront': 1.350000023841858, 'communityFeatureDEPRECATED': False, 'dashcamOnly': False, 'directAccelControlDEPRECATED': False, 'enableApgsDEPRECATED': False, 'enableBsm': False, 'enableCameraDEPRECATED': False, 'enableDsu': False, 'enableGasInterceptor': False, 'experimentalLongitudinalAvailable': False, 'fingerprintSource': 'can', 'flags': 0, 'fuzzyFingerprint': False, 'hasStockCameraDEPRECATED': False, 'isPandaBlackDEPRECATED': False, 'lateralTuning': {'pid': {'kf': 0.0}}, 'longitudinalActuatorDelayLowerBound': 0.15000000596046448, 'longitudinalActuatorDelayUpperBound': 0.15000000596046448, 'longitudinalTuning': {'deadzoneBP': [0.0], 'deadzoneV': [0.0], 'kf': 1.0, 'kiBP': [0.0], 'kiV': [1.0], 'kpBP': [0.0], 'kpV': [1.0]}, 'mass': 1700.0, 'maxLateralAccel': 10.0, 'maxSteeringAngleDegDEPRECATED': 0.0, 'minEnableSpeed': -1.0, 'minSpeedCanDEPRECATED': 0.0, 'minSteerSpeed': 0.0, 'networkLocation': 'fwdCamera', 'notCar': False, 'openpilotLongitudinalControl': False, 'pcmCruise': True, 'radarTimeStep': 0.05000000074505806, 'radarUnavailable': False, 'rotationalInertia': 2906.976806640625, 'safetyConfigs': [{'safetyModel': 'noOutput', 'safetyParam': 0, 'safetyParam2DEPRECATED': 0, 'safetyParamDEPRECATED': 0}], 'safetyModelDEPRECATED': 'silent', 'safetyModelPassiveDEPRECATED': 'silent', 'safetyParamDEPRECATED': 0, 'startAccel': 0.0, 'startingAccelRateDEPRECATED': 0.0, 'startingState': False, 'steerActuatorDelay': 0.0, 'steerControlType': 'torque', 'steerLimitAlert': False, 'steerLimitTimer': 1.0, 'steerRateCostDEPRECATED': 0.0, 'steerRatio': 13.0, 'steerRatioRear': 0.0, 'stopAccel': -2.0, 'stoppingControl': True, 'stoppingDecelRate': 0.800000011920929, 'tireStiffnessFront': 1000000.0, 'tireStiffnessRear': 1000000.0, 'transmissionType': 'unknown', 'vEgoStarting': 0.5, 'vEgoStopping': 0.5, 'wheelSpeedFactor': 1.0, 'wheelbase': 2.700000047683716}, 'logMonoTime': 110583639279, 'valid': True} ...Sign out

**Comment by kaledz** [comment]
I just ordered a comma power so hopefully that will help

**Comment by kaledz** [comment]
> I have modified the fingerprinting. Can you please try updating mazda-master and let me know if it works this time? I assume you are not using comma power and this may be the issue.

What should i do after i install the comma power. I just got it today.

**Comment by kaledz** [comment]
> Comma power has been installed now.

Can you give me the new fingerprints now

**Comment by kaledz** [comment]
Happy to do so but the issue now is that Car Parms is not showing up with any info. I did make it public to be viewed - 68d096a70c3f77be|2023-06-29--08-48-17 

Do you have any suggestions?

Also, I found this in the normal log - 

   'value': b'{"carFingerprint": "MAZDA 3 2019", "steerRatio": 16.119251251220703, "stiffnessFactor": 1.0094643831'
                                               b'253052, "angleOffsetAverageDeg": -1.736435055732727}'},

**Comment by MoreTore** [comment]
Seems like it fingerprinted the car properly now.

**Comment by kaledz** [comment]
> Seems like it fingerprinted the car properly now.

I tried mazda master and it is not working (its says not supported)

See updated fingerprint below from my last drive on 9.2 new mazda master. Quick question do i neee to leave it on the new software installed (mazda master) when you do the updatw remotely? 

log: 
carParams
{'carParams': {'alternativeExperience': 1,
               'autoResumeSng': True,
               'carFingerprint': 'mock',
               'carFw': [{'address': 1840,
                          'brand': 'mazda',
                          'bus': 0,
                          'ecu': 'eps',
                          'fwVersion': b'BCKA-3216X-E\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'>\x00', b'"\xf1\x88'],
                          'responseAddress': 1848,
                          'subAddress': 0},
                         {'address': 1892,
                          'brand': 'mazda',
                          'bus': 0,
                          'ecu': 'fwdRadar',
                          'fwVersion': b'BDTS-67XK2-E\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'>\x00', b'"\xf1\x88'],
                          'responseAddress': 1900,
                          'subAddress': 0},
                         {'address': 1888,
                          'brand': 'mazda',
                          'bus': 0,
                          'ecu': 'abs',
                          'fwVersion': b'BHCB-4300F-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'>\x00', b'"\xf1\x88'],
                          'responseAddress': 1896,
                          'subAddress': 0},
                         {'address': 1798,
                          'brand': 'mazda',
                          'bus': 0,
                          'ecu': 'fwdCamera',
                          'fwVersion': b'BDGF-67WK2-K\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'>\x00', b'"\xf1\x88'],
                          'responseAddress': 1806,
                          'subAddress': 0},
                         {'address': 1840,
                          'brand': 'ford',
                          'bus': 0,
                          'ecu': 'eps',
                          'fwVersion': b'BCKA-3216X-E\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'>\x00', b'"\xf1\x88'],
                          'responseAddress': 1848,
                          'subAddress': 0},
                         {'address': 1892,
                          'brand': 'ford',
                          'bus': 0,
                          'ecu': 'fwdRadar',
                          'fwVersion': b'BDTS-67XK2-E\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'>\x00', b'"\xf1\x88'],
                          'responseAddress': 1900,
                          'subAddress': 0},
                         {'address': 1888,
                          'brand': 'ford',
                          'bus': 0,
                          'ecu': 'abs',
                          'fwVersion': b'BHCB-4300F-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'>\x00', b'"\xf1\x88'],
                          'responseAddress': 1896,
                          'subAddress': 0},
                         {'address': 1798,
                          'brand': 'ford',
                          'bus': 0,
                          'ecu': 'fwdCamera',
                          'fwVersion': b'BDGF-67WK2-K\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'>\x00', b'"\xf1\x88'],
                          'responseAddress': 1806,
                          'subAddress': 0}],
               'carName': 'mock',
               'carVin': '00000000000000000',
               'centerToFront': 1.350000023841858,
               'communityFeatureDEPRECATED': False,
               'dashcamOnly': False,
               'directAccelControlDEPRECATED': False,
               'enableApgsDEPRECATED': False,
               'enableBsm': False,
               'enableCameraDEPRECATED': False,
               'enableDsu': False,
               'enableGasInterceptor': False,
               'experimentalLongitudinalAvailable': False,
               'fingerprintSource': 'can',
               'flags': 0,
               'fuzzyFingerprint': False,
               'hasStockCameraDEPRECATED': False,
               'isPandaBlackDEPRECATED': False,
               'lateralTuning': {'pid': {'kf': 0.0}},
               'longitudinalActuatorDelayLowerBound': 0.15000000596046448,
               'longitudinalActuatorDelayUpperBound': 0.15000000596046448,
               'longitudinalTuning': {'deadzoneBP': [0.0], 'deadzoneV': [0.0], 'kf': 1.0, 'kiBP': [0.0], 'kiV': [1.0], 'kpBP': [0.0], 'kpV': [1.0]},
               'mass': 1700.0,
               'maxLateralAccel': 10.0,
               'maxSteeringAngleDegDEPRECATED': 0.0,
               'minEnableSpeed': -1.0,
               'minSpeedCanDEPRECATED': 0.0,
               'minSteerSpeed': 0.0,
               'networkLocation': 'fwdCamera',
               'notCar': False,
               'openpilotLongitudinalControl': False,
               'pcmCruise': True,
               'radarTimeStep': 0.05000000074505806,
               'radarUnavailable': False,
               'rotationalInertia': 2906.976806640625,
               'safetyConfigs': [{'safetyModel': 'noOutput', 'safetyParam': 0, 'safetyParam2DEPRECATED': 0, 'safetyParamDEPRECATED': 0}],
               'safetyModelDEPRECATED': 'silent',
               'safetyModelPassiveDEPRECATED': 'silent',
               'safetyParamDEPRECATED': 0,
               'startAccel': 0.0,
               'startingAccelRateDEPRECATED': 0.0,
               'startingState': False,
               'steerActuatorDelay': 0.0,
               'steerControlType': 'torque',
               'steerLimitAlert': False,
               'steerLimitTimer': 1.0,
               'steerRateCostDEPRECATED': 0.0,
               'steerRatio': 13.0,
               'steerRatioRear': 0.0,
               'stopAccel': -2.0,
               'stoppingControl': True,
               'stoppingDecelRate': 0.800000011920929,
               'tireStiffnessFront': 1000000.0,
               'tireStiffnessRear': 1000000.0,
               'transmissionType': 'unknown',
               'vEgoStarting': 0.5,
               'vEgoStopping': 0.5,
               'wheelSpeedFactor': 1.0,
               'wheelbase': 2.700000047683716},
 'logMonoTime': 169197892474,
 'valid': True}
{'carParams': {'alternativeExperience': 1,
               'autoResumeSng': True,
               'carFingerprint': 'mock',
               'carFw': [{'address': 1840,
                          'brand': 'mazda',
                          'bus': 0,
                          'ecu': 'eps',
                          'fwVersion': b'BCKA-3216X-E\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'>\x00', b'"\xf1\x88'],
                          'responseAddress': 1848,
                          'subAddress': 0},
                         {'address': 1892,
                          'brand': 'mazda',
                          'bus': 0,
                          'ecu': 'fwdRadar',
                          'fwVersion': b'BDTS-67XK2-E\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'>\x00', b'"\xf1\x88'],
                          'responseAddress': 1900,
                          'subAddress': 0},
                         {'address': 1888,
                          'brand': 'mazda',
                          'bus': 0,
                          'ecu': 'abs',
                          'fwVersion': b'BHCB-4300F-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'>\x00', b'"\xf1\x88'],
                          'responseAddress': 1896,
                          'subAddress': 0},
                         {'address': 1798,
                          'brand': 'mazda',
                          'bus': 0,
                          'ecu': 'fwdCamera',
                          'fwVersion': b'BDGF-67WK2-K\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'>\x00', b'"\xf1\x88'],
                          'responseAddress': 1806,
                          'subAddress': 0},
                         {'address': 1840,
                          'brand': 'ford',
                          'bus': 0,
                          'ecu': 'eps',
                          'fwVersion': b'BCKA-3216X-E\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'>\x00', b'"\xf1\x88'],
                          'responseAddress': 1848,
                          'subAddress': 0},
                         {'address': 1892,
                          'brand': 'ford',
                          'bus': 0,
                          'ecu': 'fwdRadar',
                          'fwVersion': b'BDTS-67XK2-E\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'>\x00', b'"\xf1\x88'],
                          'responseAddress': 1900,
                          'subAddress': 0},
                         {'address': 1888,
                          'brand': 'ford',
                          'bus': 0,
                          'ecu': 'abs',
                          'fwVersion': b'BHCB-4300F-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'>\x00', b'"\xf1\x88'],
                          'responseAddress': 1896,
                          'subAddress': 0},
                         {'address': 1798,
                          'brand': 'ford',
                          'bus': 0,
                          'ecu': 'fwdCamera',
                          'fwVersion': b'BDGF-67WK2-K\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'>\x00', b'"\xf1\x88'],
                          'responseAddress': 1806,
                          'subAddress': 0}],
               'carName': 'mock',
               'carVin': '00000000000000000',
               'centerToFront': 1.350000023841858,
               'communityFeatureDEPRECATED': False,
               'dashcamOnly': False,
               'directAccelControlDEPRECATED': False,
               'enableApgsDEPRECATED': False,
               'enableBsm': False,
               'enableCameraDEPRECATED': False,
               'enableDsu': False,
               'enableGasInterceptor': False,
               'experimentalLongitudinalAvailable': False,
               'fingerprintSource': 'can',
               'flags': 0,
               'fuzzyFingerprint': False,
               'hasStockCameraDEPRECATED': False,
               'isPandaBlackDEPRECATED': False,
               'lateralTuning': {'pid': {'kf': 0.0}},
               'longitudinalActuatorDelayLowerBound': 0.15000000596046448,
               'longitudinalActuatorDelayUpperBound': 0.15000000596046448,
               'longitudinalTuning': {'deadzoneBP': [0.0], 'deadzoneV': [0.0], 'kf': 1.0, 'kiBP': [0.0], 'kiV': [1.0], 'kpBP': [0.0], 'kpV': [1.0]},
               'mass': 1700.0,
               'maxLateralAccel': 10.0,
               'maxSteeringAngleDegDEPRECATED': 0.0,
               'minEnableSpeed': -1.0,
               'minSpeedCanDEPRECATED': 0.0,
               'minSteerSpeed': 0.0,
               'networkLocation': 'fwdCamera',
               'notCar': False,
               'openpilotLongitudinalControl': False,
               'pcmCruise': True,
               'radarTimeStep': 0.05000000074505806,
               'radarUnavailable': False,
               'rotationalInertia': 2906.976806640625,
               'safetyConfigs': [{'safetyModel': 'noOutput', 'safetyParam': 0, 'safetyParam2DEPRECATED': 0, 'safetyParamDEPRECATED': 0}],
               'safetyModelDEPRECATED': 'silent',
               'safetyModelPassiveDEPRECATED': 'silent',
               'safetyParamDEPRECATED': 0,
               'startAccel': 0.0,
               'startingAccelRateDEPRECATED': 0.0,
               'startingState': False,
               'steerActuatorDelay': 0.0,
               'steerControlType': 'torque',
               'steerLimitAlert': False,
               'steerLimitTimer': 1.0,
               'steerRateCostDEPRECATED': 0.0,
               'steerRatio': 13.0,
               'steerRatioRear': 0.0,
               'stopAccel': -2.0,
               'stoppingControl': True,
               'stoppingDecelRate': 0.800000011920929,
               'tireStiffnessFront': 1000000.0,
               'tireStiffnessRear': 1000000.0,
               'transmissionType': 'unknown',
               'vEgoStarting': 0.5,
               'vEgoStopping': 0.5,
               'wheelSpeedFactor': 1.0,
               'wheelbase': 2.700000047683716},
 'logMonoTime': 219203863252,
 'valid': True}


...
Sign out

**Comment by MoreTore** [comment]
I do not have access to your device 68d096a70c3f77be.

It seems like the car was able to be fingerprinted on route 68d096a70c3f77be|2023-06-29--08-48-17

The fingerprint you have provided does not seem to be  using the comma power since they are all on bus 0.

**Comment by kaledz** [comment]
> I do not have access to your device 68d096a70c3f77be.
> 
> It seems like the car was able to be fingerprinted on route 68d096a70c3f77be|2023-06-29--08-48-17
> 
> The fingerprint you have provided does not seem to be  using the comma power since they are all on bus 0.
> 

Ah ok,

Thats confusing because i have comma power installed. Any ideas?

**Comment by MoreTore** [comment]
How did you get it working before? When it fingerprintednit as a 2019 Mazda 3

**Comment by kaledz** [comment]
Not sure, Ryleymcc did it for me. He said he had to force it to recognize. We tried several different branches but that the 9.2-new-mazda-master was the only one that would work since it forced recognition.

**Comment by kaledz** [comment]
> How did you get it working before? When it fingerprintednit as a 2019 Mazda 3

I would mention that i re-installed the 9.2-new-mazda3... and it works but whenever i install a different branch it wont work.
